#############################################################################
# Makefile for building: bin/GoGo
# Generated by qmake (3.0) (Qt 5.0.2) on: Fri Jun 28 07:53:32 2013
# Project:  GoGo.pro
# Template: app
# Command: /home/tzwm/Development/Qt5.0.2/5.0.2/gcc/bin/qmake -o Makefile GoGo.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Qt5.0.2/5.0.2/gcc/mkspecs/linux-g++ -I. -I. -Isrc -Iobj -I../../Qt5.0.2/5.0.2/gcc/include -I../../Qt5.0.2/5.0.2/gcc/include/QtWidgets -I../../Qt5.0.2/5.0.2/gcc/include/QtGui -I../../Qt5.0.2/5.0.2/gcc/include/QtCore -Iobj
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/tzwm/Development/Qt5.0.2/5.0.2/gcc -Wl,-rpath,/home/tzwm/Development/Qt5.0.2/5.0.2/gcc/lib
LIBS          = $(SUBLIBS) -L/home/tzwm/Development/Qt5.0.2/5.0.2/gcc/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/tzwm/Development/Qt5.0.2/5.0.2/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/gobanView.cpp \
		src/main.cpp \
		src/helper.cpp \
		src/goban.cpp \
		src/stoneItem.cpp \
		src/sidebar.cpp \
		src/controllerGTP.cpp \
		src/go.cpp obj/moc_sidebar.cpp
OBJECTS       = obj/gobanView.o \
		obj/main.o \
		obj/helper.o \
		obj/goban.o \
		obj/stoneItem.o \
		obj/sidebar.o \
		obj/controllerGTP.o \
		obj/go.o \
		obj/moc_sidebar.o
DIST          = ../../Qt5.0.2/5.0.2/gcc/mkspecs/features/spec_pre.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/shell-unix.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/unix.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/linux.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/gcc-base.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/g++-base.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/g++-unix.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/qconfig.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_bootstrap.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_clucene.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_v8.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/qt_functions.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/qt_config.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/linux-g++/qmake.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/spec_post.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/exclusive_builds.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/default_pre.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/default_pre.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/resolve_config.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/default_post.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/warn_on.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/qt.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/resources.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/moc.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/opengl.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/uic.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/thread.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/wayland-scanner.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/testcase_targets.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/exceptions.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/yacc.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/lex.prf \
		GoGo.pro \
		GoGo.pro
QMAKE_TARGET  = GoGo
DESTDIR       = bin/
TARGET        = bin/GoGo


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: GoGo.pro ../../Qt5.0.2/5.0.2/gcc/mkspecs/linux-g++/qmake.conf ../../Qt5.0.2/5.0.2/gcc/mkspecs/features/spec_pre.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/shell-unix.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/unix.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/linux.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/gcc-base.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/g++-base.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/common/g++-unix.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/qconfig.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_bootstrap.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_clucene.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_v8.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/qt_functions.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/qt_config.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/linux-g++/qmake.conf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/spec_post.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/exclusive_builds.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/default_pre.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/default_pre.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/resolve_config.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/default_post.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/warn_on.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/qt.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/resources.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/moc.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/opengl.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/uic.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/thread.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/wayland-scanner.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/testcase_targets.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/exceptions.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/yacc.prf \
		../../Qt5.0.2/5.0.2/gcc/mkspecs/features/lex.prf \
		GoGo.pro \
		/home/tzwm/Development/Qt5.0.2/5.0.2/gcc/lib/libQt5Widgets.prl \
		/home/tzwm/Development/Qt5.0.2/5.0.2/gcc/lib/libQt5Gui.prl \
		/home/tzwm/Development/Qt5.0.2/5.0.2/gcc/lib/libQt5Core.prl
	$(QMAKE) -o Makefile GoGo.pro
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/spec_pre.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/common/shell-unix.conf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/common/unix.conf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/common/linux.conf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/common/gcc-base.conf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/common/gcc-base-unix.conf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/common/g++-base.conf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/common/g++-unix.conf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/qconfig.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_bootstrap.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_clucene.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_core.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_designercomponents.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_help.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_network.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_platformsupport.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qmldevtools.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_quickparticles.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_script.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_v8.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/qt_functions.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/qt_config.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/linux-g++/qmake.conf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/spec_post.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/exclusive_builds.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/default_pre.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/default_pre.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/resolve_config.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/default_post.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/warn_on.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/qt.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/resources.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/moc.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/opengl.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/uic.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/unix/thread.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/wayland-scanner.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/testcase_targets.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/exceptions.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/yacc.prf:
../../Qt5.0.2/5.0.2/gcc/mkspecs/features/lex.prf:
GoGo.pro:
/home/tzwm/Development/Qt5.0.2/5.0.2/gcc/lib/libQt5Widgets.prl:
/home/tzwm/Development/Qt5.0.2/5.0.2/gcc/lib/libQt5Gui.prl:
/home/tzwm/Development/Qt5.0.2/5.0.2/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GoGo.pro

qmake_all: FORCE

dist: 
	@test -d obj/GoGo1.0.0 || mkdir -p obj/GoGo1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/GoGo1.0.0/ && $(COPY_FILE) --parents src/gobanView.h src/helper.h src/goban.h src/stoneItem.h src/sidebar.h src/controllerGTP.h src/go.h obj/GoGo1.0.0/ && $(COPY_FILE) --parents src/gobanView.cpp src/main.cpp src/helper.cpp src/goban.cpp src/stoneItem.cpp src/sidebar.cpp src/controllerGTP.cpp src/go.cpp obj/GoGo1.0.0/ && (cd `dirname obj/GoGo1.0.0` && $(TAR) GoGo1.0.0.tar GoGo1.0.0 && $(COMPRESS) GoGo1.0.0.tar) && $(MOVE) `dirname obj/GoGo1.0.0`/GoGo1.0.0.tar.gz . && $(DEL_FILE) -r obj/GoGo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_moc_header_make_all: obj/moc_sidebar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_sidebar.cpp
obj/moc_sidebar.cpp: ../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QDialog \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qdialog.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qglobal.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qconfig.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfeatures.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlogging.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qflags.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qnamespace.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstring.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qchar.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbytearray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrefcount.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qarraydata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiterator.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmetatype.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qisenum.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmargins.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrect.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsize.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpoint.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpalette.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcolor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qrgb.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdatastream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiodevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpair.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qbrush.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvector.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qmatrix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpolygon.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qregion.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qline.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtransform.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qimage.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpixmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qshareddata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qhash.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfont.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcursor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvariant.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdebug.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtextstream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlocale.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qset.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurlquery.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfile.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qvector2d.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/QPoint \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QPushButton \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qpushbutton.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qicon.h \
		src/sidebar.h
	/home/tzwm/Development/Qt5.0.2/5.0.2/gcc/bin/moc $(DEFINES) $(INCPATH) src/sidebar.h -o obj/moc_sidebar.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/gobanView.o: src/gobanView.cpp src/gobanView.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsView \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsview.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmetatype.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qglobal.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qconfig.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfeatures.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlogging.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qflags.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbytearray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrefcount.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qnamespace.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qarraydata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstring.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qchar.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qisenum.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainter.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrect.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsize.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpoint.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpixmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcolor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qrgb.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdatastream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiodevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiterator.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpair.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qshareddata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qhash.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qimage.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtransform.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qmatrix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpolygon.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvector.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qregion.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qline.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtextoption.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpen.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qbrush.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfont.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qscrollarea.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qframe.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmargins.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpalette.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcursor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvariant.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdebug.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtextstream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlocale.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qset.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurlquery.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfile.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qvector2d.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsscene.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsScene \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/QMouseEvent \
		src/helper.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/QPoint \
		src/stoneItem.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsItem \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsitem.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/QPainter \
		src/goban.h \
		src/controllerGTP.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/gobanView.o src/gobanView.cpp

obj/main.o: src/main.cpp ../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QApplication \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qapplication.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcoreapplication.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qnamespace.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qglobal.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qconfig.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfeatures.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlogging.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qflags.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstring.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qchar.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbytearray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrefcount.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qarraydata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiterator.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmetatype.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qisenum.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qeventloop.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpoint.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsize.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcursor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qdesktopwidget.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmargins.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrect.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpalette.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcolor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qrgb.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdatastream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiodevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpair.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qbrush.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvector.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qmatrix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpolygon.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qregion.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qline.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtransform.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qimage.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpixmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qshareddata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qhash.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfont.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvariant.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdebug.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtextstream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlocale.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qset.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurlquery.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfile.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qvector2d.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qguiapplication.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qinputmethod.h \
		src/go.h \
		src/controllerGTP.h \
		src/goban.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/QPoint \
		src/helper.h \
		src/gobanView.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsView \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsview.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainter.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtextoption.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpen.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qscrollarea.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qframe.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsscene.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsScene \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/QMouseEvent \
		src/stoneItem.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsItem \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsitem.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/QPainter \
		src/sidebar.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QDialog \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qdialog.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QPushButton \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qpushbutton.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/helper.o: src/helper.cpp src/helper.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/QPoint \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpoint.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qnamespace.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qglobal.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qconfig.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfeatures.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlogging.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qflags.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsysinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/helper.o src/helper.cpp

obj/goban.o: src/goban.cpp src/goban.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/QPoint \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpoint.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qnamespace.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qglobal.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qconfig.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfeatures.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlogging.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qflags.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsysinfo.h \
		src/helper.h \
		src/gobanView.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsView \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsview.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmetatype.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbytearray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrefcount.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qarraydata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstring.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qchar.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qisenum.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainter.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrect.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsize.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpixmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcolor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qrgb.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdatastream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiodevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiterator.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpair.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qshareddata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qhash.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qimage.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtransform.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qmatrix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpolygon.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvector.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qregion.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qline.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtextoption.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpen.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qbrush.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfont.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qscrollarea.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qframe.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmargins.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpalette.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcursor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvariant.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdebug.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtextstream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlocale.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qset.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurlquery.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfile.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qvector2d.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsscene.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsScene \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/QMouseEvent \
		src/stoneItem.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsItem \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsitem.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/QPainter \
		src/controllerGTP.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/goban.o src/goban.cpp

obj/stoneItem.o: src/stoneItem.cpp src/stoneItem.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsItem \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsitem.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qglobal.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qconfig.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfeatures.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlogging.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qflags.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qnamespace.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstring.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qchar.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbytearray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrefcount.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qarraydata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiterator.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmetatype.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qisenum.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvariant.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpair.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdebug.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qhash.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtextstream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiodevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlocale.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qshareddata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvector.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpoint.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qset.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrect.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsize.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qmatrix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpolygon.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qregion.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdatastream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qline.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpixmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcolor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qrgb.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qimage.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtransform.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/QPainter \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainter.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtextoption.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpen.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qbrush.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfont.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/QPoint
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/stoneItem.o src/stoneItem.cpp

obj/sidebar.o: src/sidebar.cpp src/sidebar.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QDialog \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qdialog.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qglobal.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qconfig.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfeatures.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlogging.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qflags.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qnamespace.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstring.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qchar.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbytearray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrefcount.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qarraydata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiterator.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmetatype.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qisenum.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmargins.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrect.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsize.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpoint.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpalette.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcolor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qrgb.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdatastream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiodevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpair.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qbrush.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvector.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qmatrix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpolygon.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qregion.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qline.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtransform.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qimage.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpixmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qshareddata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qhash.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfont.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcursor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvariant.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdebug.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtextstream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlocale.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qset.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurlquery.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfile.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qvector2d.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/QPoint \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QPushButton \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qpushbutton.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sidebar.o src/sidebar.cpp

obj/controllerGTP.o: src/controllerGTP.cpp src/controllerGTP.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/controllerGTP.o src/controllerGTP.cpp

obj/go.o: src/go.cpp src/go.h \
		src/controllerGTP.h \
		src/goban.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/QPoint \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpoint.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qnamespace.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qglobal.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qconfig.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfeatures.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlogging.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qflags.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsysinfo.h \
		src/helper.h \
		src/gobanView.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsView \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsview.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmetatype.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qbytearray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrefcount.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qarraydata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstring.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qchar.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qisenum.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainter.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qrect.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsize.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpixmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcolor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qrgb.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdatastream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiodevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlist.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qiterator.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qpair.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qregexp.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qshareddata.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qhash.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qimage.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtransform.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qmatrix.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpolygon.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvector.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qregion.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qline.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtextoption.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpen.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qbrush.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfont.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qscrollarea.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qframe.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmargins.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qpalette.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qcursor.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qevent.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qvariant.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qmap.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qdebug.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qtextstream.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qlocale.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qset.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurl.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qurlquery.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfile.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qvector2d.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsscene.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsScene \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/QMouseEvent \
		src/stoneItem.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QGraphicsItem \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qgraphicsitem.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/QPainter \
		src/sidebar.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QDialog \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qdialog.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/QPushButton \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qpushbutton.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.0.2/5.0.2/gcc/include/QtGui/qicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/go.o src/go.cpp

obj/moc_sidebar.o: obj/moc_sidebar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_sidebar.o obj/moc_sidebar.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

